---
title: "Corona virus data wrangling"
author: "Yelin Shin"
date: "5/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r message=FALSE}
library(magrittr)
library(dplyr)
library(tidyverse)
library(tidytext)
library(gutenbergr)
library(wordcloud)
library(stringr)
library(broom)
library(readxl)
library(rvest)
library(lubridate)
library(scales)
library(choroplethr)
library(gridExtra)
library(choroplethrMaps)
```

```{r message=FALSE, warning=FALSE}
# find 2019 popluation data
Wpopulation2019 <- "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)"  %>% read_html() %>% html_table(fill=TRUE) %>% .[[4]]

Wpopulation2019 <-  Wpopulation2019 %>% separate('Country or area', c("country", "erase"), sep = "\\[") %>% select(-erase,-'UN statisticalregion[4]',-'Population(1 July 2018)',-Change) 

names(Wpopulation2019)[names(Wpopulation2019) == "UN continentalregion[4]"] <- "continent"
names(Wpopulation2019)[names(Wpopulation2019) == "Population(1 July 2019)"] <- "population"
```

```{r}
Wpopulation2019$country <- tolower(Wpopulation2019$country)
Wpopulation2019$population <- as.numeric(gsub(",","",Wpopulation2019$population))

data(country.regions)
names(Wpopulation2019)[names(Wpopulation2019) == "country"] <- "region"
matched = inner_join(country.regions["region"], Wpopulation2019["region"], by ="region")

rename = setdiff(country.regions$region,matched$region)
rename

#antartica, kosovo is not exist in Wpopulation2019
Wpopulation2019$region[Wpopulation2019$region == "north macedonia"] <- "macedonia"
Wpopulation2019$region[Wpopulation2019$region == "united states"] <- "united states of america"
Wpopulation2019$region[Wpopulation2019$region == "somaliland"] <- "somalia"
Wpopulation2019$region[Wpopulation2019$region == "serbia"] <- "republic of serbia"
Wpopulation2019$region[Wpopulation2019$region == "tanzania"] <- "united republic of tanzania"
Wpopulation2019$region[Wpopulation2019$region == "bahamas"] <- "the bahamas"  
Wpopulation2019$region[Wpopulation2019$region == "dr congo"] <- "democratic republic of the congo"
Wpopulation2019$region[Wpopulation2019$region == "congo"] <- "republic of congo"   
Wpopulation2019$region[Wpopulation2019$region == "cyprus"] <- "northern cyprus"
Wpopulation2019$region[Wpopulation2019$region == "guinea-bissau"] <- "guinea bissau"
Wpopulation2019$region[Wpopulation2019$region == "eswatini"] <- "swaziland"

head(Wpopulation2019,3)
```

```{r}
# worldwide timeseries 
Wtime_covid = read_csv("https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv") 

# worldwide testing case timeseries
Wtime_testing = read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/testing/covid-testing-all-observations.csv")
names(Wtime_testing)[names(Wtime_testing) == "Cumulative total"] <- "cumulative_test"
```



```{r}
names(Wtime_covid)[names(Wtime_covid) == "Country/Region"] <- "region"
Wtime_covid$region <- tolower(Wtime_covid$region)

time_country= unique(Wtime_covid$region)
df <- data.frame(matrix(unlist(time_country), nrow=length(time_country), byrow=T))

matched2 = inner_join(country.regions["region"], Wtime_covid["region"], by ="region")
rename2 = setdiff(country.regions$region,matched2$region)
rename2

#north korea, solomon islands, somaliland, turkmenistan, vanuatu, ivory coast, northern cyprus, antarctica, lesotho
Wtime_covid$region[Wtime_covid$region == "north macedonia"] <- "macedonia"
Wtime_covid$region[Wtime_covid$region == "burma"] <- "myanmar"
Wtime_covid$region[Wtime_covid$region == "us"] <- "united states of america"
Wtime_covid$region[Wtime_covid$region == "serbia"] <- "republic of serbia"
Wtime_covid$region[Wtime_covid$region == "eswatini"] <- "swaziland"
Wtime_covid$region[Wtime_covid$region == "timor-leste"] <- "east timor"
Wtime_covid$region[Wtime_covid$region == "taiwan*"] <- "taiwan"
Wtime_covid$region[Wtime_covid$region == "tanzania"] <- "united republic of tanzania"
Wtime_covid$region[Wtime_covid$region == "bahamas"] <- "the bahamas"
Wtime_covid$region[Wtime_covid$region == "congo (kinshasa)"] <- "democratic republic of the congo"
Wtime_covid$region[Wtime_covid$region == "congo (brazzaville)"] <- "republic of congo"
Wtime_covid$region[Wtime_covid$region == "czechia"] <- "czech republic"
Wtime_covid$region[Wtime_covid$region == "guinea-bissau"] <- "guinea bissau"
Wtime_covid$region[Wtime_covid$region == "korea, south"] <- "south korea"

#summarize the number of the province/state in each country
Wtime_covid = Wtime_covid %>%
  group_by(region,Date) %>%
  summarise(confirmed = sum(Confirmed,na.rm=TRUE), recovered = sum(Recovered,na.rm=TRUE), deaths = sum(Deaths,na.rm=TRUE)) %>%
  mutate(actives = confirmed - recovered- deaths)

Wtime_covid %>%
  filter(region == "canada")

```

```{r warning=FALSE}
#getting latest update from each country's testing number
Wtime_testing <-  Wtime_testing %>% 
  separate('Entity', c("region", "erase"), sep = " - ") %>% 
  select(region,Date,cumulative_test) %>%
  group_by(region,Date)%>% # some country contains different testing number on duplicate dates 
  summarise(cumulative_test = max(cumulative_test,na.rm=TRUE)) # I grab max testing number for duplicate dates

Wtime_testing$region <- tolower(Wtime_testing$region)

testing= unique(Wtime_testing$region)
df <- data.frame(matrix(unlist(testing), nrow=length(testing), byrow=T))

matched2 = inner_join(Wtime_covid["region"], Wtime_testing["region"], by ="region")

rename3 = setdiff(Wtime_testing$region,matched2$region)
rename3

#hongkong, serbia is missing in Wtime_testing
Wtime_testing$region[Wtime_testing$region == "united states"] <- "united states of america"

```

```{r}
wtime_covid_final = left_join(Wtime_covid,Wpopulation2019, by='region') %>%
  select("Date","region","region","confirmed","recovered","deaths","actives","population")

wtime_covid_final = left_join(wtime_covid_final,Wtime_testing, by =c('region', 'Date')) %>%
  select("Date","region","region","confirmed","recovered","deaths","actives","cumulative_test","population")


write.csv(wtime_covid_final,"word_covid19_timeseries.csv")
wtime_covid_final[sample(nrow(wtime_covid_final), 3), ]
```


```{r}
w_latest_covid = wtime_covid_final %>%
  group_by(region) %>%
  filter(Date == max(Date) ) %>%
  mutate(actives = confirmed - recovered - deaths) %>%
  arrange(desc(actives))

latest_test = Wtime_testing %>%
  group_by(region) %>%
  filter(Date <= max(w_latest_covid$Date)) %>% #since sometime testing update faster than worldwide timeseries
  filter(Date == max(Date))

final.w_latest_covid = left_join(w_latest_covid, latest_test, by = "region") %>%
  mutate(cumulative_test= cumulative_test.y) %>%
  select(- c("Date.y","cumulative_test.x","cumulative_test.y")) 

write.csv(final.w_latest_covid,"word_covid19_latest.csv")
head(final.w_latest_covid,3)
```

```{r, message=FALSE, warning=FALSE}

w_latest_covid %>%
  arrange(desc(actives)) %>%
  mutate(ratio_active = actives/population * 100) %>%
  select(region, actives, ratio_active) %>%
  head(3)

w_latest_covid %>%
  mutate(ratio_active = actives/population * 100) %>%
  arrange(desc(ratio_active)) %>%
  select(region, actives, ratio_active) %>%
  head(3)


#active number / population
w_latest_covid.actives <- w_latest_covid %>%
  select(region, actives,population) %>%
  rename(region = region, value = actives)

w_latest_covid.actives_ratio <- w_latest_covid %>%
  select(region, actives,population) %>%
  mutate(active_ratio = actives/population) %>%
  rename(region = region, value = active_ratio)

grid.arrange(country_choropleth(w_latest_covid.actives, title  = "Number of active case in world"),country_choropleth(w_latest_covid.actives_ratio, title  = "Ratio of active by population in word"))
```

deep research with testing.
ratio of confirmed out of testing.

```{r}
#install.packages("plotly")
library(plotly)

confirmed.ratio = w_latest_covid %>%
  filter (!is.na(cumulative_test)) %>%
  mutate ( confirmed.ratio = (confirmed/cumulative_test) *100) %>%
  arrange( desc(confirmed.ratio))

confirmed.ratio$region <- factor(confirmed.ratio$region, levels = confirmed.ratio$region[order(confirmed.ratio$confirmed.ratio, decreasing = TRUE)]) 

ggplot(data = confirmed.ratio, aes(x = region, y=confirmed.ratio))+ theme(axis.text.x = element_text(angle=45, hjust = 1)) +  geom_bar(stat="identity")

ggplotly()
```

```{r}


```








```{r}
have_testing = w_latest_covid %>%
  filter (!is.na(cumulative_test)) %>%
  mutate ( negative = cumulative_test - confirmed,
           total = actives+recovered+deaths+negative,
           active.ratio = (actives / total )* 100,
           recover.ratio = (recovered / total )* 100,
           death.ratio = (deaths / total )* 100,
           nagative.ratio = (negative / total )* 100) %>%
  arrange(desc(cumulative_test))

top10.test <- c(have_testing$region[1:10])

top10_test=have_testing %>% gather(c("active.ratio", "recover.ratio", "death.ratio", "nagative.ratio"), key="type", value="number") %>%
  arrange(desc(cumulative_test)) %>%
  filter(region %in% top10.test)%>%
  select(-c("Date","confirmed","cumulative_test","population","negative","total","actives","recovered","deaths","negative"))

ggplot( data = top10_test, aes(x = region, y=number, fill = type)) + geom_bar(stat = "identity") +  coord_flip() + xlab("Country") +ylab("Ratio (%)") + ggtitle("Top 10 tested countries' ratio of case within testing number") + scale_fill_discrete(name = "Case type", labels = c("Active", "Death", "Negative","Recover"))


have_testing2 = have_testing %>%
  arrange((cumulative_test))

least10.test <- c(have_testing2$region[1:10])

least10_test=have_testing2 %>% gather(c("active.ratio", "recover.ratio", "death.ratio", "nagative.ratio"), key="type", value="number") %>%
  arrange(desc(cumulative_test)) %>%
  filter(region %in% least10.test)%>%
  select(-c("Date","confirmed","cumulative_test","population","negative","total","actives","recovered","deaths","negative"))

ggplot( data = least10_test, aes(x = region, y=number, fill = type)) + geom_bar(stat = "identity") +  coord_flip() + xlab("Country") +ylab("Ratio (%)") + ggtitle("Least 10 tested countries' ratio of case within testing number") + scale_fill_discrete(name = "Case type", labels = c("Active", "Death", "Negative","Recover"))


```




```{r}
# national
data(state.regions)
US.time_covid = read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")

state.regions
names(US.time_covid)[names(US.time_covid) == "state"] <- "region"
US.time_covid$region <- tolower(US.time_covid$region)

time_state= unique(US.time_covid$region)
df2 <- data.frame(matrix(unlist(time_state), nrow=length(time_state), byrow=T))

matched3 = inner_join(state.regions["region"], US.time_covid["region"], by ="region")
rename3 = setdiff(state.regions$region,matched3$region)
rename3 # everything is matched. No state name change is required.


US.time_covid_final = US.time_covid %>% select(-"fips")

write.csv(US.time_covid_final,"US_covid19_timeseries.csv")
US.time_covid_final[sample(nrow(US.time_covid_final), 3), ]
```




```{r}
#national "https://www.cdc.gov/nchs/nvss/vsrr/COVID19/index.htm"

N_death_detail = read_csv("https://data.cdc.gov/api/views/hc4f-j6nb/rows.csv?accessType=DOWNLOAD&bom=true&format=true")

N_death_race = read_csv("https://data.cdc.gov/api/views/pj7m-y5uh/rows.csv?accessType=DOWNLOAD&bom=true&format=true")


```

```{r}
# site for US detail data : https://github.com/nytimes/covid-19-data
# count and show graph how many article is release about corona virus by time series & how many article about corona is there : https://developer.nytimes.com/docs/articlesearch-product/1/overview


```
